# Generated by Django 3.2.15 on 2022-09-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='dogs_age',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='dogs_breed',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='dogs_name',
        ),
    ]
